### ISSUE TITLE
Foo Class's functions time and space complexity analysis

### ISSUE THREAD

**Issue by EmreArapcicUevak** [EmreArapcicUevak/CodeSmash-Hackaton-2023#3]
# Time Complexity Analysis of the *IsBuyerWinner* function

```java
public static int IsBuyerWinner(String[][] codeList,String[] shoppingCart) {
	String[] currentCodeList = codeList[0];
	int curIndex = 0;
	boolean patternFound = true;

	for (int i = 0; i < shoppingCart.length; i++){
		// Check if there is enough elements left to compare to save time
		if (currentCodeList.length > shoppingCart.length - i)
			return 0;
		else if (checkFruit(currentCodeList[0],shoppingCart[i])) {
			patternFound = true;

			for (int j = 1; j < currentCodeList.length; j++){
				if (!checkFruit(currentCodeList[j],shoppingCart[i + 1])) {
					patternFound = false;
					break;
				}else
					i++;
			}
			
			if (patternFound){
				if (codeList.length - 1 != curIndex){
					curIndex++;
					currentCodeList = codeList[curIndex];
				}else
					return 1;
			}
		}
	}

	return 0;
    }
```

---

First lets take a look at the **checkFruit** function and figure out it's time and space complexity

```java
private static boolean checkFruit(String codeFruit, String shoppingFruit){
	return codeFruit.equals(shoppingFruit) || codeFruit.equals("anything") && !shoppingFruit.equals("nothing");
}
```

## checkFruit's time complexity

If we take a good look we can see that we have 3 equals operations both of with in the worst case if the string are both equal length **n** the time complexity will be O(n) but since we can also comparing them to the string "anything" (8 characters) and "nothing" (7 characters) we also have to make sure that **n** is bigger then these two, so in total we have **O(max(n,8))**

If we were to just look at values of n as n just gets bigger and bigger the time complexity would be **O(n)**; since n will surpass 8 eventually so we can conclude that the time complexity is O(n).

Also if we take the fact that **n** is rising to infinity. We can also say that the worst case then would be if both of the string were equal the same size, had all the same characters, and ended up being equal to one another. Since our Strings aren't all the same we can say that **n** can be the size of the BIGGEST string, and we can take that all the string are equal to said biggest string.

## checkFruit's space complexity

Since we aren't making any new variables the amount of new space we are making is 0; hence our space complexity is **O(1)**

---

## IsBuyerWinner's Space Complexity

In the entire function definition we only have 3 variable declarations.

```java
        String[] currentCodeList = codeList[0];
	int curIndex = 0;
	boolean patternFound = true;
```

Keep in mind that `currentCodeList` just contains the memory address of the 1st element of the matrix and not the copy of the entire element. In other words it has the reference to the object in memory. And the other two and just plain base variables; this all means that no matter how much our input changes we only have 3 variables in our code so our space complexity is **O(1)**.

## IsBuyerWinner's Time Complexity

If we take a look at our first loop that we have
```java
for (int i = 0; i < shoppingCart.length; i++){
```

At the worst case we would have to check to the entire shoppingCart array meaning if we say that **m** is the length of our array the loop would go m times because of the following line of code

```java
if (currentCodeList.length > shoppingCart.length - i)
			return 0;
```

This line of code ensures that at any point if we do not have enough elements to compare we will instantly break from the loop and return 0.

The other part of the if statement is 
```java
else if (checkFruit(currentCodeList[0],shoppingCart[i])) { // Remember this is O(n)
			patternFound = true;

			for (int j = 1; j < currentCodeList.length; j++){ // O(o)
				if (!checkFruit(currentCodeList[j],shoppingCart[i + 1])) { // O(n)
					patternFound = false; // 1
					break; // 1
				}else
					i++; // 1
			}
			
			if (patternFound){ // 1
				if (codeList.length - 1 != curIndex){ // 1
					curIndex++; // 1
					currentCodeList = codeList[curIndex]; // 1
				}else 
					return 1; // 1
			}
		}
	}
```

Here we can see that we used O(o) to mark the inner loop `for (int j = 1; j < currentCodeList.length; j++)`. This is because if we take a look at the the sub arrays of the matrix `codeLists` and assume that all of them have the size of the biggest element of the entire matrix **o**; then we can say this loop runs **o** \* **n** times in the worst case. Leading us to our final conclusion that this functions has a time complexity of:

`O(m * n * o)`
Where 
n - size of the **BIGGEST** string in either the shopping or code arrays
m - size of the shopping cart array
o - size of the **BIGGEST**  sub array of all the arrays in the codeArray matrix

**Comment by VedadSiljic** [comment]
looks good
